### ISSUE TITLE
Images & Metadata

### ISSUE THREAD

**Issue by SimAlvarez** [contao-themes-net/odd-theme-bundle#10]
Hi,
thanks for the great theme!
I would like to know, if it is possible to give out the metadata of an image in the frontend. For example, under the headerpicture/headerslider or at the newslist with pictures. Any hint, where that information could be added, is appreciated.

- Simone

**Comment by seibtph** [comment]
You can add the metadata if you edit the image in the file system. You can also overwrite the meta data on a image element. Hope this helps.
