### ISSUE TITLE
Bei Stuck-Navi anderes Logo wählen

### ISSUE THREAD

**Issue by webprintz** [contao-themes-net/odd-theme-bundle#11]
Wo könnte ich die Anpassung machen, wenn ich für das Logo (stuck) ein anderes auswählen möchte.
Hab leider noch nicht herausgefunden, in welches Template das Logo eingebaut ist.

**Comment by mr2017x** [comment]
Hallo Webprintz,

du kannst das Navi-Logo über den Artikel 01/01 Logo anpassen.

**Comment by webprintz** [comment]
Kann ich dort auch ein anderes Logo für die kleinere Variante auswählen?
Also wenn die Klasse stuck aktiv ist

**Comment by mr2017x** [comment]
nativ nicht, da das Logo schlicht größenmäßig angepasst wird.

**Comment by seibtph** [comment]
@webprintz Das ist relativ einfach anpassbar.

Du kannst in dem Artikel, wo das Logo platziert ist, einfach noch ein zweites Bild-Element anlegen und dem eine Klasse geben, z. B. `stuck-logo`. 

Füge dann folgendes CSS in die custom.scss ein:

```
.stuck-logo {
	display: none;
} 

.stuck .stuck-logo {
	display: block;
}

.stuck .navbar-brand .ce_image:not(.stuck-logo) {
	display: none;
}
```
