### ISSUE TITLE
Release 1.4.3

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/odd-theme-bundle#12]
Guten Morgen,

ich warte seit dem Bug mit dem Headroom.js auf das release 1.4.3, wie ist da der Release-Zyklus, da ich ungern vorab die Änderung einspielen möchte um nicht im nachhinein Probleme mit dem Update zu bekommen?

LG

**Comment by mr2017x** [comment]
Guten Morgen,

nun ist die 1.4.3 drin, leider ist das Problem mit den Vor/Zurück Buttons auf dem Desktop gelöst, aber auf der mobilen Version leider noch nicht.

**Comment by seibtph** [comment]
Welches Problem genau meinst du?

**Comment by mr2017x** [comment]
mobil werden zurück und vorwärts anstelle der slider im Kopf angezeigt - Interessanterweise nicht in "mobile-view" bspw im Desktop Chrome...

**Comment by mr2017x** [comment]
Slider korrekt: <   >

**Comment by seibtph** [comment]
Kannst du bitte mal einen Screenshot von dem Fehler machen? Und welches Gerät und welchen Browser nutzt du?

Leider konnte ich das noch nicht reproduzieren.

**Comment by mr2017x** [comment]
OnePlus7, Android 10, Chrome, aber auch FF.

![Unbenannt](https://user-images.githubusercontent.com/31145556/93989651-79dc0d00-fd8a-11ea-85a6-cadee2577562.png)

**Comment by mr2017x** [comment]
Eure Demo ist kein Problem, gehe davon aus, dass es mit dem "fixierten Header" zu tun hat. Warum nur mobil ist mir unklar.

**Comment by seibtph** [comment]
Ok, jetzt hatte ich es auch gesehen. Ich habe die Version 1.4.4 veröffentlicht, damit sollte es jetzt behoben sein.

**Comment by mr2017x** [comment]
passtm, danke dir, woran lag das nun noch?

**Comment by seibtph** [comment]
Eine Anpassung im Javascript habe ich gemacht, da waren noch ein paar Zeilen, die eigentlich überflüssig waren. Es wurde trotzdem versucht das Headroom-Skript auszuführen, daher kam es zu dem Fehler.
