### ISSUE TITLE
Newsletter Anmeldung auf der Startseite

### ISSUE THREAD

**Issue by speedweb** [contao-themes-net/odd-theme-bundle#13]
wenn die Newsletter Anmeldung auf das Notifikationscenter umgestellt wird, wird der bereich auf der Startseite falsch angezeigt.
(wird unten einfach gerade dargestellt und nicht bis zum Footer gefüllt)

Dem div Container wird folgende Class hinzugefügt "mod_newsletterSubscribeNotificationCenter nl-footer skw-tl block"
In der Demo wird die Class "mod_subscribe nl-footer skw-tl block" hinzugefügt und der Bereich richtig angezeigt.

## Screenshots
https://1drv.ms/u/s!ArdiqdLnofD5lBey3Vhctps0mrGZ

**Comment by seibtph** [comment]
Ist mit Version 1.4.3 behoben. Danke für das Melden. ;)
