### ISSUE TITLE
Stylesheet Pfade werden nicht gefunden

### ISSUE THREAD

**Issue by S-Snowball** [contao-themes-net/odd-theme-bundle#14]
Hallo,

ich wollte soeben das ODD Theme mir genauer anschauen, daher habe ich mir lokal auf meinen PC eine Contao installation installiert und anschließend das ODD Theme. Im Backend ist soweit alle in Ordnung, ich habe das ODD Theme installeiert und die Datenbank eingespielt, die Artikel aus der Demo sind im Backend vorhanden.

Allerdings kann ich die Preview nicht öffnen, ich bekomme die Contao Fehlermeldung

```
Es ist ein Fehler aufgetreten
....

Wie kann ich das Problem lösen?
Öffnen Sie die aktuelle Log-Datei im Ordner var/logs und suchen Sie die zugehörige Fehlermeldung (normalerweise die letzte).
....
```
In der var/logs habe ich nun folgendes stehen:
`request.CRITICAL: Uncaught PHP Exception ScssPhp\ScssPhp\Exception\CompilerException: "`../../../files/odd/scss/_custom_colors` file not found for @import: line: 16, column: 1" at C:\xampp\htdocs\vendor\scssphp\scssphp\src\Compiler.php line 5231 {"exception":"[object] (ScssPhp\\ScssPhp\\Exception\\CompilerException(code: 0): `../../../files/odd/scss/_custom_colors` file not found for @import: line: 16, column: 1 at C:\\xampp\\htdocs\\vendor\\scssphp\\scssphp\\src\\Compiler.php:5231)"} []`

Ich habe unter files nachgesehen, die der ODD Ordner mit den besagten files ist da. Ich habe auch versucht einen direkten Pfad in der materializes_win anzugeben, allerdings ohne Erfolg. Es kommt der selbe Fehler.

Gibt es dazu einen Tipp wie man das Theme auf Windows ans laufen bekommt?

**Comment by seibtph** [comment]
Ich habe das nochmal mit Xampp und Laragon getestet und das funktionierte alles soweit. Am Theme dürfte der Fehler nicht liegen. 

Hast du deine Installation direkt in htdocs liegen und gar nicht in einem Unterordner? Ich bin da nach folgender Installation vorgegangen und habe einen Virtual Host angelegt: https://qlick.ch/de/installation-des-contao-cms-auf-windows-10-mit-xampp/ Wenn du das so wie beschrieben einrichtest, sollte es auf jeden Fall funktionieren.
