### ISSUE TITLE
Contao 4.10 Theme Installation - Hintergrund-Prozess wurde unerwartet beendet

### ISSUE THREAD

**Issue by Sebanit** [contao-themes-net/odd-theme-bundle#15]
Einen wunderschönen Guten Abend und ein freundliches Hallo an alle,

ich haben Contao 4.10 installiert (Provider Alfahosting) und versucht über den Manager ein Theme (ODD Theme) zu installieren. Trotz Erhöhung der Serverlimits bricht der Hintergundprozess immer ab.

Folgendes gibt die Konsole aus:

-----------

composer update (mittels Resolver Cloud)
> Resolving dependencies using Composer Cloud v2.4.11
!!! Current server is sponsored by: Contao Association !!!
[6.4MiB/0.21s] Loading composer repositories with package information
[6.9MiB/0.35s] Updating dependencies
[2956.4MiB/31.44s] Your requirements could not be resolved to an installable set of packages.
[2956.4MiB/31.44s]
Problem 1
- Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.4
- Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.3
- Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.2
- Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.1
- Installation request for contao-themes-net/odd-theme-bundle ^1.4 -> satisfiable by contao-themes-net/odd-theme-bundle[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4].
- Conclusion: don't install doctrine/doctrine-bundle 2.2.1
- contao-themes-net/odd-theme-bundle 1.4.0 requires contao-bootstrap/bundle ~2.0 -> satisfiable by contao-bootstrap/bundle[2.0.0, 2.1.0, 2.1.1].
- contao-bootstrap/bundle 2.0.0 requires contao-bootstrap/core ~2.0 -> satisfiable by contao-bootstrap/core[2.0.0, 2.0.1, 2.0.2, 2.0.3].
- contao-bootstrap/bundle 2.1.0 requires contao-bootstrap/core ~2.0 -> satisfiable by contao-bootstrap/core[2.0.0, 2.0.1, 2.0.2, 2.0.3].
- contao-bootstrap/bundle 2.1.1 requires contao-bootstrap/core ~2.0 -> satisfiable by contao-bootstrap/core[2.0.0, 2.0.1, 2.0.2, 2.0.3].
- contao-bootstrap/core 2.0.0 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.11, 1.12.12, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
- contao-bootstrap/core 2.0.1 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.11, 1.12.12, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
- contao-bootstrap/core 2.0.2 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.11, 1.12.12, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
- contao-bootstrap/core 2.0.3 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.11, 1.12.12, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
- Can only install one of: doctrine/doctrine-bundle[1.10.0, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.10.1, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.10.2, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.10.3, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.11.0, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.11.1, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.11.2, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.0, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.1, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.10, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.11, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.12, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.2, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.3, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.4, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.5, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.6, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.7, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.8, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.12.9, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.8.0, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.8.1, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.9.0, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.9.1, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.0, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.1, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.10, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.11, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.12, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.13, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.2, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.3, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.4, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.5, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.6, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.7, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.8, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.6.9, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.7.0, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.7.1, 2.2.1].
- Can only install one of: doctrine/doctrine-bundle[1.7.2, 2.2.1].
- Installation request for doctrine/doctrine-bundle (locked at 2.2.1) -> satisfiable by doctrine/doctrine-bundle[2.2.1].
[2956.4MiB/31.44s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[551.7MiB/33.41s] Memory usage: 551.72MB (peak: 2957.24MB), time: 33.42s.
[551.7MiB/33.41s] Finished Composer Cloud resolving.
# Cloud Job ID 9i9SystQ4twdYZa5CtVIwyreRqolWhgH57ZRe05kdi0NN0ZAW3yD1qRf6FUMyZvb5RsIHvWZ19uHm3TSJCeE9E1InOqiJI63OfQ6IQGAKjL54gYjAgtQSd failed

-----------

Was kann ich tun um diesen Fehler zu beheben? Leider bin ich was Contao angeht nicht der allergrösste Fuchs ;-) 

Danke im voraus

**Comment by seibtph** [comment]
Wenn du es genau wie in der Anleitung beschrieben machst, sollte die Installation ohne Fehler durchlaufen:

1. Bei allen vorhandenen Paketen auf Aktualisieren klicken. In dem Fall sind dies nur die Contao-Pakete. Danach noch NICHT auf Änderungen anwenden klicken, sondern erst die nächsten Schritte befolgen.
2. Im Menü auf Entdecken klicken und im Eingabefeld nach ODD Theme suchen.
3. Das Paket mit dem Namen ODD Theme hinzufügen.
4. Im Menü auf Pakete klicken und im Fußbereich auf Änderungen anwenden klicken.

https://pdir.de/docs/de/contao/themes/odd/installation/
