### ISSUE TITLE
Buttons are shrinked in new Version

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/odd-theme-bundle#16]
Good Morning,

after updating Contao and therefore also odd theme to last Version buttons are not in right size anymore (minimal size). Furthermore it seems as the set "link text" field is gone also in backend? It seems as would have contao had have changed something in the backend.?

Would you please check that?

Thanks in advance!

**Comment by seibtph** [comment]
It's fixed in version 1.4.9.
