### ISSUE TITLE
Unkown option: gallery_gs_grid

### ISSUE THREAD

**Issue by najbo** [contao-themes-net/odd-theme-bundle#24]
## Bug description
After installing 1.7.1 odd theme, the "gallery_bs_grid" model is not available anymore. Error on frontpage
Notice : the bs_ fields were deleted in the database after 1.7.1 update.
Package contao/bootstrap is present in /vendor/contao-bootstrap/grid/

Log file :
[2021-12-15 18:46:41] request.CRITICAL: Uncaught PHP Exception Exception: "Could not find template "gallery_bs_grid"" at /home/clients/.../sites/estoppey-addor.ch/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php line 158 {"exception":"[object] (Exception(code: 0): Could not find template \"gallery_bs_grid\" at /home/clients/.../sites/estoppey-addor.ch/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:158)"} []

## Screenshots (article) :
![Capture d’écran 2021-12-15 184845](https://user-images.githubusercontent.com/18056783/146239285-743f1477-8861-43ed-8188-ff3c387fcc1b.png)

## Environment
php 8.0

**Comment by seibtph** [comment]
Maybe you can try to update the theme. Which contao version do you use? I have tested this in our development page and it works. The gallery_bs_grid template should be exist.

**Comment by najbo** [comment]
Hi,

I use Contao 4.9.24 on PHP 8.0.13. I updated Odd theme (from contao-manager), but nothing happend.

composer update contao-themes-net/odd-theme-bundle contao/conflicts

> Resolving dependencies using Composer Cloud v3.2.0
!!! Current server is sponsored by: Contao Association !!!
[7.2MiB/0.19s] Loading composer repositories with package information
[67.6MiB/2.29s] Updating dependencies
[142.7MiB/52.82s] Lock file operations: 0 installs, 9 updates, 0 removals
[142.7MiB/52.83s]   - Upgrading beberlei/assert (v3.3.1 => v3.3.2)
[142.7MiB/52.83s]   - Upgrading doctrine/orm (2.10.3 => 2.10.4)
[142.7MiB/52.83s]   - Upgrading scheb/2fa-backup-code (v5.13.0 => v5.13.1)
[142.7MiB/52.83s]   - Upgrading scheb/2fa-bundle (v5.13.0 => v5.13.1)
[142.7MiB/52.84s]   - Upgrading scheb/2fa-trusted-device (v5.13.0 => v5.13.1)
[142.7MiB/52.84s]   - Upgrading simplepie/simplepie (1.5.6 => 1.5.7)
[142.7MiB/52.84s]   - Downgrading symfony/deprecation-contracts (v3.0.0 => v2.5.0)
[142.7MiB/52.84s]   - Upgrading symfony/service-contracts (v2.4.1 => v2.5.0)
[142.7MiB/52.85s]   - Upgrading terminal42/escargot (1.3.0 => 1.4.0)
[142.0MiB/52.86s] Writing lock file
[80.8MiB/52.91s] <warning>Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.</warning>
[80.8MiB/52.92s] <warning>Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.</warning>
[80.8MiB/52.92s] <warning>Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.</warning>
[80.8MiB/52.92s] <warning>Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.</warning>
[81.3MiB/52.92s] Memory usage: 81.27MB (peak: 1587.67MB), time: 52.93s.
[81.3MiB/52.93s] Finished Composer Cloud resolving.





composer install
$ /opt/php8.0/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Zurich /home/clients/xyz/sites/estoppey-addor.ch/web/contao-manager.phar composer install --prefer-dist --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 9 updates, 0 removals
  - Downloading symfony/deprecation-contracts (v2.5.0)
  - Downloading symfony/service-contracts (v2.5.0)
  - Downloading terminal42/escargot (1.4.0)
  - Downloading beberlei/assert (v3.3.2)
  - Downloading simplepie/simplepie (1.5.7)
  - Downloading scheb/2fa-bundle (v5.13.1)
  - Downloading scheb/2fa-trusted-device (v5.13.1)
  - Downloading scheb/2fa-backup-code (v5.13.1)
  - Downloading doctrine/orm (2.10.4)
  - Downgrading symfony/deprecation-contracts (v3.0.0 => v2.5.0): Extracting archive
  - Upgrading symfony/service-contracts (v2.4.1 => v2.5.0): Extracting archive
  - Upgrading terminal42/escargot (1.3.0 => 1.4.0): Extracting archive
  - Upgrading beberlei/assert (v3.3.1 => v3.3.2): Extracting archive
  - Upgrading simplepie/simplepie (1.5.6 => 1.5.7): Extracting archive
  - Upgrading scheb/2fa-bundle (v5.13.0 => v5.13.1): Extracting archive
  - Upgrading scheb/2fa-trusted-device (v5.13.0 => v5.13.1): Extracting archive
  - Upgrading scheb/2fa-backup-code (v5.13.0 => v5.13.1): Extracting archive
  - Upgrading doctrine/orm (2.10.3 => 2.10.4): Extracting archive
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
95 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Added the web/app.php file.
Added the web/index.php file.
Added the web/preview.php file.
 // Clearing the cache for the prod environment with debug                      
 // false                                                                       
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
 // Clearing the cache for the dev environment with debug                       
 // true                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
 // Warming up the cache for the prod environment with debug                    
 // false                                                                       
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   
 Trying to install assets as relative symbolic links.
 --- ----------------------------------- ------------------ 
      Bundle                              Method / Error    
 --- ----------------------------------- ------------------ 
  ✔   ContaoCoreBundle                    relative symlink  
  ✔   MultiColumnWizardBundle             relative symlink  
  ✔   NetzmachtContaoFormDesignerBundle   relative symlink  
  ✔   ContaoFaqBundle                     relative symlink  
  ✔   PdirAnimatedTimelineBundle          relative symlink  
  ✔   ContaoBootstrapCoreBundle           relative symlink  
  ✔   ContaoCommentsBundle                relative symlink  
  ✔   ThemeHelperBundle                   relative symlink  
  ✔   ContaoNewsBundle                    relative symlink  
  ✔   RockSolidFrontendHelperBundle       relative symlink  
  ✔   ContaoCalendarBundle                relative symlink  
  ✔   ContaoNewsletterBundle              relative symlink  
  ✔   PdirThemeOddBundle                  relative symlink  
  ✔   ContaoDDAdvancedClassesBundle       relative symlink  
  ✔   Terminal42ChangeLanguageBundle      relative symlink  
  ✔   ContaoBootstrapGridBundle           relative symlink  
  ✔   ContaoBootstrapNavbarBundle         relative symlink  
 --- ----------------------------------- ------------------ 
 [OK] All assets were successfully installed.                                   
 --- --------------------------------- ---------------------------------------------------------------- 
      Symlink                           Target / Error                                                  
 --- --------------------------------- ---------------------------------------------------------------- 
  ✔   web/files/odd                     files/odd                                                       
  ✔   web/files/estoppey-addor          files/estoppey-addor                                            
  ✔   web/system/modules/haste/assets   system/modules/haste/assets                                     
  ✔   system/themes/flexible            vendor/contao/core-bundle/src/Resources/contao/themes/flexible  
  ✔   web/assets                        assets                                                          
  ✔   web/system/themes                 system/themes                                                   
  ✔   system/logs                       var/logs                                                        
 --- --------------------------------- ---------------------------------------------------------------- 
Done! Please open the Contao install tool or run contao:migrate on the command line to make sure the database is up-to-date.
# Process terminated with exit code 0
# Result: OK
