### ISSUE TITLE
Hi, nach der Installation des ODD Theme mit Demodaten erscheinen keine Seiten/Artikel im Backend.

### ISSUE THREAD

**Issue by rolandloch** [contao-themes-net/odd-theme-bundle#25]

**Comment by rolandloch** [comment]
Hi, nach der Installation des ODD Theme mit Demodaten erscheinen keine Seiten/Artikel im Backend. Bei der Installation gibt es keine Fehlermeldungen. Die SQL-Dateien liegen brav im Theme-Manager.
Contao 4.12
PHP >= 8.1

**Comment by seibtph** [comment]
Hallo Roland,

mit PHP 8 gibt es aktuell noch ein Problem beim ODD Theme. Eine neue Version wird aber bald folgen. Am besten wäre du stellst erstmal auf 7.4 um und probierst den Import wieder.
