### ISSUE TITLE
Text und Icon Element ohne Elementschutz 

### ISSUE THREAD

**Issue by Frank15Bromisch** [contao-themes-net/odd-theme-bundle#28]
## Bug description
Das Element Text und Icon hat nur die Möglichkeit, es den Gästen zu zeigen, aber nicht das Element für bestimmte Gruppen zu schützen

**Comment by MDevster** [comment]
@seibtph please update palette.

**Comment by seibtph** [comment]
Wenn du das ODD Theme bzw. das Theme Components Bundle aktualisierst sollte das Feld nun auch verfügbar sein.
