### ISSUE TITLE
Contao 4.13.0 - Frontend: Es ist ein Fehler aufgetreten

### ISSUE THREAD

**Issue by MichaelSFD** [contao-themes-net/odd-theme-bundle#29]
Hallo,

nach "Nature" habe ich nun auch versucht "ODD" und "MATE" unter Contao 4.13.0 zu installieren. Leider auch hier beide Male erfolglos.

"MATE" bricht bereits während der Installation ab.

Bei "ODD" passiert dasselbe wie bei "Nature". Will man das Frontend aufrufen, kommt bei jeder Seite die Contao-Fehlerseite "Es ist ein Fehler aufgetreten".

Auch hier ist in der Dateiverwaltung der Ordner "odd" leer.

Ich nutze als öffentlichen Ordner "public", nicht "web".
PHP-Version ist 7.4.

Schon mal vielen Dank und viele Grüße

Michael

**Comment by MichaelSFD** [comment]
Hallo,

aus einer älteren Test-Installation von ODD hatte ich noch die Daten aus der Dateiverwaltung und habe die einfach mal in die aktuelle Installation hochgeladen.

Und es hat funktioniert.

Der Fehler liegt also bei den fehlenden Dateien  im Ordner "odd".

Viele Grüße

Michael

**Comment by MDevster** [comment]
Fixed in version 2.0.1.
