### ISSUE TITLE
Fehler "resource from [...] was blocked due to MIME type [...] mismatch"

### ISSUE THREAD

**Issue by Fortunox** [contao-themes-net/odd-theme-bundle#3]
## Bug description
Fehlermeldung "The resource from “http://www.xyz.tld/?v=39e9932b” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)." tritt in Konsole permanent (d.h. beim Aufruf des Frontend als auch vom Backend) nach Installation des Theme Odd auf.
Es wird ein "vertümmelter" Skriptaufruf generiert: <script src="?v=39e9932b"></script>

## Steps to reproduce
1. Contao 4.9.0 (ebenso mit 4.8.8) vollständig neu installiert (Fehlermeldung tritt in Konsole noch nicht auf)
2. Theme Odd gemäß Installationsanleitung importiert/installiert (Fehlermeldung in Konsole sichtbar sowohl beim Aufruf des Frontend als auch des Backends)
3. Installation auf anderem Server durchgeführt: Genau gleiches Verhalten

## Expected behavior
Keine Fehlermeldung

## Screenshots
[https://community.contao.org/de/showthread.php?77201-Fehler-quot-resource-form-was-blocked-due-to-MIME-type-mismatch-quot-(Odd-Theme)](https://community.contao.org/de/showthread.php?77201-Fehler-quot-resource-form-was-blocked-due-to-MIME-type-mismatch-quot-(Odd-Theme))

## Environment
Contao: 4.9.0 (ebenso bei 4.8.8)
Odd-Theme: 1.1.7
PHP Version: 7.3.14-5+0\~20200202.52+debian9\~1.gbpa71879
System: Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64

**Comment by MDevster** [comment]
@Fortunox will be fixed in version 1.1.8

**Comment by Fortunox** [comment]
Perfect, many thanks!
