### ISSUE TITLE
Änderung der Schriftart über _custom_variables.scss nur im Debug-Modus wirksam

### ISSUE THREAD

**Issue by janborg** [contao-themes-net/odd-theme-bundle#34]
## Bug description
Ich möchte die Schriftart im ODD-Theme anpassen. Die Änderung wird wirksam solange ich im dev-Environment (Debug-Mode) bin. Sobald ich im prod-Environment bin, wird die Fallback-Schriftart Muli bzw. Cabin verwendet. Ich habe alle Caches etc. geleert, aber die neue Schrift wird nicht wirksam. Sobald ich den Debu-Modus aktiviere, ist auch die geänderte Schrift aktiviert.

## Steps to reproduce
Ich habe gemäß der Dokumentation (https://pdir.de/docs/de/contao/themes/odd/customization/#schriftart-einbinden) eine andere Schriftart konfiguriert und die zugehörigen Dateien im files Ordner abgelegt. Alle Änderungen in der Datei "_custom_variables.scss" eingetragen.

## Environment
Sowohl auf meinem Lokalen Entwicklungssystem, wie auch auf meiner "Live"-Seite bei uberspace.
Contao 4.13.6
Odd-Theme 2.0.1

**Comment by janborg** [comment]
Ich habe versucht, herauszufinden, wo der Unterschied herkommt und folgendes festgestellt:

In "dev" habe ich am Ende des <head> zwei link Elemente, eins vom bootstrap und eins vom odd-theme:
`<link rel="stylesheet" type="text/css" media="all" href="bundles/pdirthemeodd/bootstrap/dist/css/bootstrap.min.css?v=cfb090fd">`
`<link rel="stylesheet" href="assets/css/web_bundles_pdirthemeodd_scss_odd.scss.css?v=cfb090fd">`

Im zweiten stylesheet finden sich die Angaben @font-face aus dem odd-bundle (odd.scss / Muli und Cabin) und auch meine (Roboto-Regular) aus der `_custom_variables.scss`.

In "prod" werden diese beiden stylesheets dann nur noch als eine Datei ausgegeben und ich finde darin zwar noch die Angaben @font-face Muli und Cabin aus der odd.scss, aber nicht mehr meine Angabe @font-face aus der `_custom_variables.scss`.

`<link rel="stylesheet" type="text/css" media="all" href="assets/css/bootstrap.min.css,odd.scss-b5a056a1.css">`

**Comment by MDevster** [comment]
Hallo Jan, das Problem ist meist der etwas sehr hartnäckige Cache der Browser. Ich nehme an, wenn du die Seite im "Privaten Modus" des Browsers aufrufst, wird die Seite richtig dargestellt.
Du kannst auch einmal versuchen einen "Hard refresh" mit der Tastenkombination Strg + F5 zu machen. Das erzwingt, dass neu laden der aktuellen Seite und das leeren des Browser Caches.

**Comment by janborg** [comment]
Danke, da hatte ich wohl doch noch einen der vielen Caches nicht bedacht!
