### ISSUE TITLE
Best Way to implement language Switch

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/odd-theme-bundle#4]
Good Evening,

i am wondering what would be the best way to implement a language switch (flags or just language-code) in this theme or is there already something prepared (or in general in your themes?)

Thanks in Advances

**Comment by seibtph** [comment]
You can install the changelanguage extension from terminal42: https://extensions.contao.org/?q=changelangu&pages=1&p=terminal42%2Fcontao-changelanguage
