### ISSUE TITLE
Fehler beim Template-Import mit Contao V4.9.1

### ISSUE THREAD

**Issue by reibaur** [contao-themes-net/odd-theme-bundle#5]
## Bug description
Beim Import des Templates *"odd_theme_contao_demo_4.9.x_installtool.sql"* in Contao 4.9.1 wird folgende Fehlermeldung angezeigt: *"Der Import konnte nicht abgeschlossen werden! Ist die Datenbank aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?"*

Ein anschließender Versuch die sql Datei mit phpMyAdmin zu importieren, brachte die folgende Fehlermeldung: *#1062 - Doppelter Eintrag '117' für Schlüssel 'PRIMARY'*

Die Installation in der gleichen Umgebung jedoch mit Contao 4.4 funktionierte erfolgreich.

## Steps to reproduce
1. Neue Installation von Contao 4.9.1

2. Theme Odd Bundle laut Anleitung bis Step *"4 Datenbank importieren"* installieren

3. Datenbank *"odd_theme_contao_demo_4.9.x_installtool.sql"* importieren

   > *"Der Import konnte nicht abgeschlossen werden! Ist die Datenbank aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?"*

## Expected behavior
Datenbank erfolgreich importiert.

## Screenshots
Keine

## Environment
Contao v4.9.1
MySQL v5.7.28
PHP-Version 7.4 oder 7.3

Installation bei zwei unterschiedlichen Hostern mit gleichem Verhalten.

**Comment by MDevster** [comment]
@reibaur Hast du für den Test unter 4.4 und 4.9 die gleiche Datenbank verwendet? Wenn ja, sind sehr wahrscheinlich bereits Daten vorhanden und dann hat das Install-Tool Probleme die Datenbank zu importieren. (Doppelter Eintrag '117' )

**Comment by reibaur** [comment]
Ja, ich habe die gleiche Datenbank genommen. Allerdings war die Erst-Installation in die leere Datenbank mit Contao 4.9. Dabei trat der Fehler auf.
Zwischen den Installationen habe ich die Datenbank komplett gelöscht (drop).

**Comment by dominikbrand** [comment]
Hatte heute bei der Installation den selben Fehler. Meines Erachtens nach liegt das Problem daran, dass vorgängig nicht alle Spalten in den entsprechenden Tabellen zugefügt werden. Z.B. fehlt die Spalte bs_tab_nav_position in der Tabelle tl_content (und noch weitere...). Jedoch gemäss SQL odd_theme_contao_demo_4.9.x_installtool.sql werden diese Spalten gebraucht und der Import schlägt fehl weil es sie nicht gibt.

**Comment by MDevster** [comment]
@dominikbrand Problem ist, dass scheinbar nicht alle Abhängigkeiten installiert wurden. Das Bootstrap Core-Bundle ist als Abhängigkeit definiert und damit sollte auch die Tabs-Erweiterung (https://github.com/contao-bootstrap/tab) installiert werden. Nur scheint diese zu fehlen und daher werden die Felder auch nicht angelegt.

Mögliche Problemlösung:

Nicht die Bootstrap-Pakete, sondern alle bereits installierten Pakete (also in der Regel nur Contao).

1. Contao-Manager aufrufen
2. Login
3. Contao-Manager starten
4. Auf Menüpunkt Pakete klicken
5. Pakete aktualisieren klicken
6. NICHT Änderungen anwenden klicken
7. Auf Menüpunkt Entdecken klicken
8. contao-bootstrap/bundle suchen
9. Bei contao-bootstrap/bundle auf hinzufügen klicken
10. Auf Menüpunkt Pakete klicken
11. Auf Änderungen anwenden klicken

Bei Contao Bootstap gibt es dazu auch bereits Tickets:
https://github.com/contao-bootstrap/tab/issues/8#issuecomment-565487041
oder im Forum
https://community.contao.org/de/showthread.php?76833-contao-bootstrap-grid-bricht-bei-Installation-ab&p=517301&viewfull=1#post517301

**Comment by NinaG** [comment]
Habe das selbe Problem beim Installieren der 4.9er .sql im Install-Tool: "Der Import konnte nicht abgeschlossen werden! Ist die Datenbank aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?!

Ich habe eine frische Contao 4.4-Installation (ohne Inhalt) zu einer 4.8 und dann einer 4.9 aktualisiert (notwendig, damit das beim Hoster korrekt läuft). Danach alle Schritte wie in der Installations-Anleitung von https://pdir.de/docs/de/contao/themes/odd/installation/ gemacht. Dabei bin ich auf den Fehler getroffen und habe auch die Schritte wie hier im Thread vom 20. April empfohlen gemacht. Danach nochmal versucht, aber selber Fehler.

Ich wollte dieses Theme sehr gerne für einen Kunden installieren, etwas anpassen und ihm dann zum Kauf raten (damit es ohne Backlink ist). Aber wenn ich es nicht mal installiert bekomme, ist das natürlich schwierig. Hat jemand einen Tipp wie ich es doch noch zum Laufen bekomme?

**Comment by reibaur** [comment]
@NinaG Meine "Lösung" war am Ende, dass ich die Installation des Themes zuerst in Contao 4.4 durchgeführt und erst danach Contao auf 4.9 aktualisiert habe. Nicht schön, aber es hat funktioniert.

**Comment by MDevster** [comment]
Geht aktuell leider nicht anders. Demnächst wird es aber möglich sein auch in eine bestehende Installation die Demo-Inhalte zu importieren.
