### ISSUE TITLE
Logo im Header mit Transition

### ISSUE THREAD

**Issue by zonky2** [contao-themes-net/odd-theme-bundle#56]
Beim Scrollen nach unten wird die Headerzeile kleiner und damit auch das Logo - leider springt das sehr von einem Status in den nächsten... eine `transition` auf `height` wäre sicher schön(er)

**Comment by zonky2** [comment]
könnte man die Höhe als Inline-CSS setzen? Im Template sollte das doch aus den Bildeigenschaften ermittelbar sein - oder?

**Comment by seibtph** [comment]
Ja das wäre möglich. Ich muss mal schauen ob und wie wir das am besten ins Theme integrieren.

**Comment by seibtph** [comment]
Das Feature ist in der Version 3.4.0 implementiert. Du musst nur das Template des Logo auf `logo_odd.html.twig` umstellen.
