### ISSUE TITLE
Newsletter Template - {{request_token}}

### ISSUE THREAD

**Issue by gww-its** [contao-themes-net/odd-theme-bundle#59]
## Bug description
the use of `{{request_token}}` in templates are deprecated. So use with contao 5.3 leads to failure
[https://docs.contao.org/dev/framework/request-tokens/](https://docs.contao.org/dev/framework/request-tokens/)

## Steps to reproduce
Using the template "nl_default_footer_odd" for register to a newsletter in the footer

## Expected behavior
sending a mail to the requester

## Environment
Contao 5.3 with php8.3.3

## Solution
instead of using `{{request_token}}` in the template use 
`<?= $this->requestToken ?>`

**Comment by seibtph** [comment]
Fixed in version 3.5.0
