### ISSUE TITLE
Fixed Headroom breaks pre/back Buttons, Icons into top-navigation

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/odd-theme-bundle#8]
Hi @MDevster ,

sadly it was to soon closed here.

thank you very much i'll give it a try. But first question was not regarding to fonts but to "foreign"/"own" icons, e.g png. How can i place them properly in that top-top-navigation (right beneath facebook).

sadly if i comment headroom out by // it doesn't show <> on sliders but pre and back, if remove the comment // it is all fine.

**Comment by MDevster** [comment]
Please excuse me, my solution would be as follows:

- Use picture element
- Set image size to 40x40 pixels
- Enable Overwrite Metadata
- Insert image link
- Add CSS class for example 'icon

Then insert the following into custom.scss:

.navbar-top .ce_text.icon { float: right; }

See screenshots for details

![Artikel › 01 02 Top Navbar › Inhaltselemente   odd pdir dev](https://user-images.githubusercontent.com/10244240/85848760-ff5f1980-b7a9-11ea-8ee5-8df4fb6e02a3.png)
![Artikel › 01 02 Top Navbar › Inhaltselemente › Inhaltselement ID 1147 bearbeiten   odd pdir dev](https://user-images.githubusercontent.com/10244240/85848764-00904680-b7aa-11ea-852a-16f5b6091856.png)
![Odd Theme Demo - odd - contao theme](https://user-images.githubusercontent.com/10244240/85848769-025a0a00-b7aa-11ea-9b30-2dafa506779f.png)

**Comment by seibtph** [comment]
The css should be `.navbar-top .ce_image.icon { float: right; }` not .ce_text ;)

**Comment by mr2017x** [comment]
i saw that :-) but still there is a problem with commenting out headroom.js. it breaks other js

`Uncaught ReferenceError: Headroom is not defined
    at HTMLDocument.<anonymous> (bootstrap.min.js,all.min.js,scripts.js-e7d7bb64.js:108)
    at e (jquery.min.js-e7f3ea1e.js:2)
    at t (jquery.min.js-e7f3ea1e.js:2)`
